Repository oveleon/contao-component-style-manager, pull requests merged in 2024-08, with the labels that each got.

#105 Symfony 7 preparations
  .editorconfig
  composer.json
  config/commands.yaml
  config/migrations.yaml
  config/routes.yaml
  contao/config/config.php
  contao/dca/tl_style_manager.php
  contao/dca/tl_style_manager_archive.php
  contao/languages/de/tl_style_manager.xlf
  contao/languages/de/tl_style_manager_archive.xlf
  contao/languages/en/tl_style_manager.xlf
  contao/languages/en/tl_style_manager_archive.xlf
  contao/languages/fr/tl_style_manager.xlf
  contao/languages/fr/tl_style_manager_archive.xlf
  public/stylemanager.css
  public/stylemanager.css.map
  public/stylemanager.scss
  src/Command/ObjectConversionCommand.php
  src/ContaoManager/Plugin.php
  src/Controller/BackendModule/ImportController.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/ContaoComponentStyleManagerExtension.php
  src/EventListener/AddCustomRegexpListener.php
  src/EventListener/DataContainer/StyleManagerArchiveListener.php
  src/EventListener/DataContainer/StyleManagerListener.php
  src/EventListener/ExecutePostActionsListener.php
  src/EventListener/LoadFormFieldListener.php
  src/EventListener/ParseTemplateListener.php
  src/EventSubscriber/KernelRequestSubscriber.php
  src/Migration/Version30/ObjectConversionMigration.php
  src/Model/StyleManagerArchiveModel.php
  src/Model/StyleManagerModel.php
  src/StyleManager/Config.php
  src/StyleManager/StyleManager.php
  src/StyleManager/Styles.php
  src/StyleManager/Sync.php
  src/Twig/StyleManagerExtension.php
  src/Widget/ComponentStyleSelect.php
Labels: enhancement

#107 Do not use `$dc->id` for slug generator
  src/EventListener/DataContainer/StyleManagerListener.php
Labels: bug, unconfirmed

#110 Handle strict type errors
  src/ContaoManager/Plugin.php
  src/Controller/BackendModule/ImportController.php
  src/EventSubscriber/KernelRequestSubscriber.php
  src/StyleManager/Config.php
  src/StyleManager/StyleManager.php
  src/StyleManager/Styles.php
  src/StyleManager/Sync.php
  src/Twig/StyleManagerExtension.php
  src/Widget/ComponentStyleSelect.php
Labels: bug
